app/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import db, login_manager

@login_manager.user_loader
def load_user(user_id):
        return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    email = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    notes = db.relationship('Note', backref='user', lazy='dynamic')
    tags = db.relationship('Tag', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username

class Note(db.Model):
    __tablename__ = 'notes'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    tag_id = db.Column(db.Integer, db.ForeignKey('tags.id'))
    public = db.Column(db.Boolean)

class Tag(db.Model):
    __tablename__ = 'tags'
    id = db.Column(db.Integer, primary_key=True)
    tag = db.Column(db.String(128))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    notes = db.relationship('Note', backref='tag', lazy='dynamic')

    def __repr__(self):
        return '<Tag %r>' % self.tag

app/notes/forms.py
from flask_wtf import Form
from wtforms import SubmitField, TextAreaField, SelectField, StringField, BooleanField
from wtforms.validators import Required, Length, Regexp

class NoteForm(Form):
    body = TextAreaField('What is on your mind?', validators=[Required()])
    tag = SelectField('Tag')
    public = BooleanField('open to public view?')
    submitNote = SubmitField('submit')

class EditForm(Form):
    body = TextAreaField('What is on your mind?', validators=[Required()])
    public = BooleanField('open to public view?')
    submitNote = SubmitField('submit')

class DeleteNote(Form):
    submit = SubmitField('Delete')

class TagForm(Form):
    tag = StringField('Tag')
    submitTag = SubmitField('submit')

app/__init__.py
from flask import Flask
from config import config
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth_route.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    config[config_name].init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main_route as main_blueprint
    app.register_blueprint(main_blueprint)

    from .notes import notes_route as notes_blueprint
    app.register_blueprint(notes_blueprint)

    from .auth import auth_route as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main_route = Blueprint('main_route', __name__)

from . import views, errors

app/main/views.py
from flask import render_template
from flask_login import current_user
from . import main_route

@main_route.route('/')
def index():
    return render_template('index.html')

app/notes/__init__.py
from flask import Blueprint

notes_route = Blueprint('notes_route', __name__)

from . import views

app/notes/views.py
from flask import render_template, url_for, flash, redirect, abort, request
from flask_login import login_required, current_user
from sqlalchemy import extract
from . import notes_route
from .. import db
from .forms import NoteForm, DeleteNote, TagForm, EditForm
from ..helpers import TimeHelper
from ..models import Note, Tag

@notes_route.context_processor
def utility_processor():
    return dict(format_time=TimeHelper.format_time, get_day=TimeHelper.get_day, get_month=TimeHelper.get_month, get_year=TimeHelper.get_year)

def user_logged_in(current_user, note):
    if current_user.id != note.user_id:
        return abort(403)

@notes_route.route('/notes')
@login_required
def notes():
    noteForm = NoteForm()
    noteForm.tag.choices = [(t.id, t.tag) for t in Tag.query.filter(Tag.user_id == current_user.id)]
    notes = Note.query.order_by(Note.timestamp.desc()).filter(Note.user_id == current_user.id)
    return render_template('notes/notes.html', noteForm=noteForm, tagForm=TagForm(), deleteNote=DeleteNote(), notes=notes)

@notes_route.route('/notes/tag/<int:id>')
@login_required
def notes_by_tag(id):
    noteForm = NoteForm()
    noteForm.tag.choices = [(t.id, t.tag) for t in Tag.query.filter(Tag.user_id == current_user.id)]
    notes = Note.query.order_by(Note.timestamp.desc()).filter(Note.tag_id == id).filter(Note.user_id == current_user.id)
    return render_template('notes/notes.html', noteForm=noteForm, tagForm=TagForm(), deleteNote=DeleteNote(), notes=notes)

@notes_route.route('/notes/month/<int:month>/<int:year>')
@login_required
def notes_by_month(year, month):
    noteForm = NoteForm()
    noteForm.tag.choices = [(t.id, t.tag) for t in Tag.query.filter(Tag.user_id == current_user.id)]
    notes = Note.query.order_by(Note.timestamp.desc()).filter(extract('year', Note.timestamp) == year).filter(extract('month', Note.timestamp) == month).filter(Note.user_id == current_user.id)
    return render_template('notes/notes.html', noteForm=noteForm, tagForm=TagForm(), deleteNote=DeleteNote(), notes=notes)

@notes_route.route('/notes/year/<int:year>')
@login_required
def notes_by_year(year):
    noteForm = NoteForm()
    noteForm.tag.choices = [(t.id, t.tag) for t in Tag.query.filter(Tag.user_id == current_user.id)]
    notes = Note.query.order_by(Note.timestamp.desc()).filter(extract('year', Note.timestamp) == year).filter(Note.user_id == current_user.id)
    return render_template('notes/notes.html', noteForm=noteForm, tagForm=TagForm(), deleteNote=DeleteNote(), notes=notes)

@notes_route.route('/notes/day/<int:day>/<int:month>/<int:year>')
@login_required
def notes_by_day(day, month, year):
    noteForm = NoteForm()
    noteForm.tag.choices = [(t.id, t.tag) for t in Tag.query.filter(Tag.user_id == current_user.id)]
    notes = Note.query.order_by(Note.timestamp.desc()).filter(extract('year', Note.timestamp) == year).filter(extract('month', Note.timestamp) == month).filter(extract('day', Note.timestamp) == day).filter(Note.user_id == current_user.id)
    return render_template('notes/notes.html', noteForm=noteForm, tagForm=TagForm(), deleteNote=DeleteNote(), notes=notes)


@notes_route.route('/add-note/', methods=['POST'])
def add_note():
    body = request.form['body']
    public = False
    if body:
        if 'public' in request.form:
            public = True
        tag = Tag.query.filter(Tag.id == request.form['tag']).first()
        note = Note(body=body, user=current_user._get_current_object(), tag=tag, public=public)
        db.session.add(note)
    return redirect(url_for('notes_route.notes'))

@notes_route.route('/add-tag/', methods=['POST'])
def add_tag():
    data = request.form['tag']
    if data:
        tag = Tag(tag=data, user=current_user._get_current_object())
        db.session.add(tag)
    return redirect(url_for('notes_route.notes'))

@notes_route.route('/note/<int:id>')
def note(id):
    note = Note.query.get_or_404(id)
    if not hasattr(current_user, 'id') and note.public == False:
        return abort(403)
    return render_template('notes/note.html', note=note)

@notes_route.route('/edit-note/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_note(id):
    note = Note.query.get_or_404(id)
    user_logged_in(current_user, note)
    noteForm = EditForm()
    if noteForm.validate_on_submit():
        note.body = noteForm.body.data
        db.session.add(note)
        flash('Note updated')
        return redirect(url_for('notes_route.note', id=note.id))
    noteForm.body.data = note.body
    return render_template('notes/edit-note.html', noteForm=noteForm, note=note)

@notes_route.route('/delete-note/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_note(id):
    user_logged_in(current_user, Note.query.get_or_404(id))
    deleteNote = DeleteNote()
    if deleteNote.validate_on_submit():
        Note.query.filter(Note.id == id).delete()
        db.session.commit()
        return redirect(url_for('notes_route.notes'))
    return render_template('notes/delete-note.html', deleteNote=deleteNote)

app/templates/base.html
<!doctype html>
<html>
<head>
  {% block head %}
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css', _external=True) }}">
  {% endblock %}
</head>
<body>

  {% include 'components/flashed-messages.html' %}

  {% block body %}
  {% endblock %}
  <script src="{{ url_for('static', filename='script.js', _external=True) }}"></script>
</body>
</html>

app/templates/components/flashed-messages.html
{% for message in get_flashed_messages() %}
  <p class="notification">{{ message }}</p>
{% endfor %}

app/templates/components/login-menu.html
<ul class="login-menu">
  {% if (current_user.is_authenticated) %}
  <li><a href="{{ url_for('auth_route.logout') }}">Logout</a></li>
  {% else %}
  <li><a href="{{ url_for('auth_route.login') }}">Login</a></li>
  {% endif %}
</ul>

app/templates/index.html
{% extends 'base.html' %}

{% block body %}

{% include 'components/login-menu.html' %}

hi

{% endblock %}

app/templates/notes/delete-note.html
{% extends 'base.html' %}

{% block body %}

{% include 'components/login-menu.html' %}

<form method="POST">
  {{ deleteNote.hidden_tag() }}
  {{ deleteNote.submit() }}
</form>


{% endblock %}

app/templates/notes/edit-note.html
{% extends 'base.html' %}

{% block body %}

{% include 'components/login-menu.html' %}

<a class="option" href="{{ url_for('notes_route.notes') }}">Back to notes</a>
<a class="option" href="{{ url_for('notes_route.note', id=note.id) }}">View note</a>
<a class="option" href="{{ url_for('notes_route.notes_by_tag', id=note.tag_id) }}">{{note.tag.tag}}</a>

<form method="POST">
  {{ noteForm.hidden_tag() }}

  <div class="field">
    {% for message in noteForm.body.errors %}
    <p class="field-error">{{ message }}</p>
    {% endfor %}
    {{ noteForm.body.label }} {{ noteForm.body(class='input') }}
    </p>
  </div>

{{ noteForm.submitNote() }}

</form>


{% endblock %}

app/templates/notes/note.html
{% extends 'base.html' %}

{% block body %}

{% include 'components/login-menu.html' %}

{% if (current_user.is_authenticated) %}
<a class="option" href="{{ url_for('notes_route.notes') }}">Back to notes</a>
<a class="option" href="{{ url_for('notes_route.edit_note', id=note.id) }}">Edit note</a>
<a class="option" href="{{ url_for('notes_route.notes_by_tag', id=note.tag_id) }}">{{note.tag.tag}}</a>

<a class="option" href="{{ get_month(note.timestamp).month_id }}">{{ get_month(note.timestamp).month }}</a>
<a class="option" href="{{ get_year(note.timestamp) }}">{{ get_year(note.timestamp) }}</a>
{% endif %}

<p>{{ format_time(note.timestamp) }}</p>
<p>{{ note.body }}</p>

{% endblock %}

app/templates/notes/notes.html
{% extends 'base.html' %}

{% block body %}

{% include 'components/login-menu.html' %}

<h1>{{current_user.username}}'s notes</h1>

<div class="col">
  <form method="POST" name="note" action="{{ url_for('notes_route.add_note') }}">
    {{ noteForm.hidden_tag() }}

    <div class="field">
      {% for message in noteForm.body.errors %}
      <p class="error">{{ message }}</p>
      {% endfor %}
      {{ noteForm.body.label }}
      {{ noteForm.body(class='input') }}
    </div>

    {{ noteForm.tag.label }}
    {{ noteForm.tag(class='input') }}

    {{ noteForm.public.label }}
    {{ noteForm.public(value='y', class='input') }}

    {{ noteForm.submitNote() }}
  </form>

  <form method="POST" name="tag" action="{{ url_for('notes_route.add_tag') }}">
    {{ tagForm.hidden_tag() }}

    <div class="field">
      {% for message in tagForm.tag.errors %}
      <p class="error">{{ message }}</p>
      {% endfor %}
      {{ tagForm.tag.label }}
      {{ tagForm.tag(class='input') }}
    </div>

    {{ tagForm.submitTag() }}
  </form>
</div>

<div class="col">
  <div class="notes">
    {% for note in notes %}
    <article class="note">
      <div class="options">
        <a class="option" href="{{ url_for('notes_route.edit_note', id=note.id) }}">Edit</a>
      </div>
      <p class="date">
        <a class="date-item" href="{{ url_for('notes_route.notes_by_day', day=get_day(note.timestamp), year=get_year(note.timestamp), month=get_month(note.timestamp).month_id) }}">{{ get_day(note.timestamp) }}</a>
        <a class="date-item" href="{{ url_for('notes_route.notes_by_month', year=get_year(note.timestamp), month=get_month(note.timestamp).month_id) }}">{{ get_month(note.timestamp).month }}</a>
        <a class="date-item" href="{{ url_for('notes_route.notes_by_year', year=get_year(note.timestamp)) }}">{{ get_year(note.timestamp) }}</a>
      </p>
      <p class="date">
        <a class="option" href="{{ url_for('notes_route.notes_by_tag', id=note.tag_id) }}">{{ note.tag.tag }}</a>
      </p>

      {% if note.public %}
      <a href="{{ url_for('notes_route.note', id=note.id) }}" class="option">
        public url
      </a>
      {% endif %}

      <div class="note-body">
        <p>{{ note.body }}</p>
      </div>

      <form id="delete-form-{{note.id}}" class="delete-form" method="POST" action="{{ url_for('notes_route.delete_note', id=note.id) }}">
        {{ deleteNote.hidden_tag() }}
        {{ deleteNote.submit() }}
      </form>
    </article>
    {% endfor %}
  </div>
</div>

{% endblock %}